version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-my-solution
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8080"
    #network_mode: host
    
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
